### ISSUE TITLE
error importing Dimension

### ISSUE THREAD

**Issue by chriswaudby** [rafaqz/DimensionalData.jl#111]
Hi,

Newbie here so apologies if this is something obvious or stupid, but I can't figure out what's going on here. I've got a fresh julia installation (1.4, OS X) and have added DimensionalData, but after `using DimensionalData`, I find that `Dimension` is undefined. Everything else seems to work just fine:

```
julia> using DimensionalData

julia> Dimension
ERROR: UndefVarError: Dimension not defined

julia> X
X

julia> using DimensionalData: Dimension
ERROR: UndefVarError: Dimension not defined

julia> import DimensionalData.Dimension
WARNING: could not import DimensionalData.Dimension into Main

julia> import DimensionalData.Dim

julia> DimensionalArray()
ERROR: MethodError: no method matching DimensionalArray()
Closest candidates are:
  DimensionalArray(::A, ::D, ::R, ::String) where {T, N, D<:Tuple, R<:Tuple, A<:AbstractArray{T,N}} at /Users/chris/.julia/packages/DimensionalData/ECqye/src/array.jl:90
```

My installation status is:
```
(@v1.4) pkg> status
Status `~/.julia/environments/v1.4/Project.toml`
  [0703355e] DimensionalData v0.8.0
  [50d2b5c4] Lazy v0.15.0
  [c2839fe3] NMRTools v0.1.0 [`~/.julia/dev/NMRTools`]
  [189a3867] Reexport v0.2.0
```

Weirdly, it's a problem that seems to have arisen in the last 12 hours or so. A package that I'd been starting to develop, https://github.com/chriswaudby/NMRTools.jl, was using this fine, but when I pushed to github travis started flagging this as an error. I've reset my own julia installation and now I am also having this issue - unfortunately I didn't preserve my old state first!

Any ideas what's going on? Apologies again if this is something stupid :)

Chris

**Comment by rafaqz** [comment]
I don't think `Dimension` existed in 0.8, it was `AbstractDimension`. That just changed today on master and on 0.9 with the huge PR I just merge. A lot of types have changed to make the package less verbose. Hopefully that will be the last major change to types for a while. 

0.9 isn't quite registered yet, it should be in a few hours. Until then you can use the master branch directly.

What are you trying to do with `Dimension` by the way?

**Comment by rafaqz** [comment]
I realised the docs for `Dimension` are terrible. Will fix that. `Dimension` is the abstract supertype of all the dimensions. You would only use it in method dispatch.

**Comment by chriswaudby** [comment]
OK, I'd downloaded the package to take a look at it so perhaps I was inadvertently working with some of your commits, and then after resetting I've been back to the 0.8 branch. I'll wait to see what happens with 0.9.

I'm trying to make a wrapper for `DimensionalArray` that carries metadata not associated with a particular axis. So I'm forwarding calls to `metadata`, but wanted to create a more convenient form, e.g. `metadata(A, X)` to return the metadata for the X axis of A:

```julia
metadata(d::NMRData, dim::Union{Dimension,Type{<:Dimension}}) = metadata(dims(d, dim))
```

By the way, is there any way to make the default metadata for `X`, `Y`, `Z` and `Ti` a `Dict` rather than `nothing`? It would be convenient to be able to create axes with `X(x1)` rather than `X(x1, UnknownGrid(), Dict())`.

**Comment by rafaqz** [comment]
Ok I thought that might have happened. 

The `metadata` field is a good idea. In GeoData.jl (that inherits from DimensionalData) `GeoArray` has a `metadata` field already. Would that help to just have it here in `DimensionalArray`? Your convenient `metadata(A, X)` form could also be added here, I think it's useful.

BTW, if you do need to, adding a wrapper is probably hard work. I's easier to extend `AbstractDimensionalArray` with your own type. Just copy the `DimensionalArray`, its very little code.

As for the `Dict()`, you can also do 
```julia
X(x1; metadata=Dict())
```
We can't really do `metadata=Dict()` by default because we use dims for `getindex` wrappers as well, and we want them not to allocate the `Dict`, as they are otherwise suitable for high performance inner loops.

Sorry there are a lot of changes happening right now, its not easy getting the structure or syntax of this right, and  I'm past the point of having any examples to follow.

**Comment by rafaqz** [comment]
`DimensionalArray` hasa `metadata` field and  a `metadata(A, X)` method on master.
