### ISSUE TITLE
How do you construct a dimensional array?

### ISSUE THREAD

**Issue by haberdashPI** [rafaqz/DimensionalData.jl#15]
It's not super transparent from the documentation how you construct a DimensionalArray. For example, I tried to do:

```julia
DimensionalArray(rand(10,2),(Time(),X()))
```

And this did not work. I'm sure I could figure out how to do it if I read the source, but it seems like it would be good to have some examples of how to create an array somewhere in the README or docs.

**Comment by rafaqz** [comment]
No the docs aren't amazing yet. I'm mostly trying to build functionality to support GeoData.jl and things are still changing a lot. You can always look through the tests fo more examples (for most julia packages it's usually a good idea most of it has to be in there, and it should be fairly easy to read)

But I will add some better examples for constructing `DimensionalArrays`.

For your example: currently you can't construct a dimensional array with that much information. I could allow a basic type that just has dim names and no values, but currently the dims are _indexes_.

So in `Time` you would want to put some array or range of DateTime or unitful times matching the length of the dimension, or a tuple of numbers/unitful times for the start and end points. Then you can then use them to index. Otherwise all you are getting form the package is dimension order...

So something like this (but use whatever you want for the indexes):
```
using Unitful
A = DimensionalArray(rand(10,2),(Time((1u"d", 10u"d")), X(10:10:20)))
julia> A[Time(At(3u"d"))]
2-element DimensionalArray{Float64,1,Tuple{X{StepRange{Int64,Int64},Nothing,Order{DimensionalData.Forward,DimensionalData.Forward}}},Tuple{Time{Quantity{Float64,𝐓,Unitful.FreeUnits{(d,),𝐓,nothing}},Nothing,Order{DimensionalData.Forward,DimensionalData.Forward}}},Array{Float64,1}}:
 0.507109957352055 
 0.5135603136916305

```

**Comment by rafaqz** [comment]
No, really it is useful feedback! there should be more examples of how to actually use this, I'm just not sure when I will write them.

Honestly DimensionalArray was kind of an afterthought/placeholder -  this package was built to extend more than to use directly. But I guess DimensionalArray is actually useful.

**Comment by rafaqz** [comment]
Ok interesting. I haven't tried using it like that. 

What happens to the axes when you index a slice of the MetaArray? Does it keep both the axes and your metadata?

DimensionalData is designed to be extended more than wrapped - inheriting from AbstractDimensionalArray. Adding a dims field and a rebuild method is nearly all you need to do.
They should work and rebuild in place with your metadata and updated dims, for most base or stats methods you use on it (missing a few still).

As an example, the definition of DimensionalArray is tiny and you don't even need all of that (you can choose to ignore refdims, they are just for plot labels and tracking slice history:
https://github.com/rafaqz/DimensionalData.jl/blob/master/src/array.jl#L79-L113

**Comment by haberdashPI** [comment]
I haven't tested MetaArray with DimensionalData, so I can't speak to that.
With AxisArray objects, I had to write a few new methods to preserve the
dimensions, but it wasn't hard. It's possible that DimensionalData is a
cleaner solution, that would make MetaArrays moot. I have to play around
with it a bit myself to see. That said, I think getting all of the
broadcast machinery right for a custom array can be a bit of a pain
sometimes, and my goal in writing it was to avoid having to reinvent the
wheel in that respect every time, so I suspect that, even if I have to
write a method here and there to get them to work together, that it could
save some time and effort.
