### ISSUE TITLE
What does the dim name Ti stand for?

### ISSUE THREAD

**Issue by musm** [rafaqz/DimensionalData.jl#154]
X,Y are common enough, but what does Ti stand for?

**Comment by rafaqz** [comment]
Time! It prints as that in the REPL too. 

You can find the reasoning in an issue way back going over the options... `Time` is solidly taken by `Dates` and used to cause constant clashes because people using this package often use `Dates`. 

And `T` is by far the most common, basically universal type parameter that would be rude to export. `Ti` sucks but it was free and it's easy to type, so that's what it is. The options were `Tm`, `Tim` etc etc. but they're all bad.

**Comment by musm** [comment]
Got it thanks!

**Comment by rafaqz** [comment]
Also being the time dimension actually has a meaning and dispatch properties, as well as just plotting on the X axis - because X would do that top. `Ti` dimension interval cell are always indexed at the `Start` of the interval for `Intervals` because they cant be `Center` - you cant do `Month(1)/2`. And a year on its own means the start of the year, not the center. Anyway, time.

**Comment by musm** [comment]
> Ti sucks but it was free and it's easy to type, so that's what it is. The options were Tm, Tim etc etc. but they're all bad.

Yeah I can't think of anything better: Ti / Tm  are about as best you can do without using `T` (sadly)
