### ISSUE TITLE
Should `val` & `data` be merged?

### ISSUE THREAD

**Issue by singularitti** [rafaqz/DimensionalData.jl#169]
It seems that `data` returns a `view` of the `AbstractDimArray`, but it can be regarded as "Return the contained value of a wrapper object", I guess? Currently `data` is not documented & conflicts with the name that is often used as a variable.

**Comment by rafaqz** [comment]
Yes `data` is basically `val`. But it is actually equivalent to `Base.parent` for arrays. It's legacy from when the design was slightly different. 

So just use `parent` as it's the standard for arrays even the tests mostly do that now (you will notice I've been actually replacing `data` with `parent` in the last few weeks)

We can fully get rid of it one day, but priorities sometimes get in the way of that kind of cleanup.

**Comment by Datseris** [comment]
a further comment that I also have been thinking about: the field of a dimension that contains the data is `val` while for dimensional arrays is `data`, and it also would be more sensible for those to be the same as well. But probably too breaking?

**Comment by rafaqz** [comment]
But they are not really the same thing. The field on the dim is `val` because it can literally be anything. `Dimension` is a wrapper/marker for marking the dimension of any thing. You will see in the new method `set` that they will be use to hold metadata or mode field to say where it should be set. So `val` is very broad. 

But `data` has to be `<: AbstractArray`. `data` is equivalent to `parent`, not `val`.

There is also `index` now for dims - which is not equivalent to `val`, `data`, or `parent` though it seems kind of like all of them.

**Comment by rafaqz** [comment]
`DimDataset` now also uses `data` to retreive it's layers of data, which is very nice for code reuse for sharing methods between `DimArray/DimDataset`.

I feel that `data` makes the most sense in those cases, but `val` is better for dims, where `data` doesn't really describe what they hold. This also means I can revert #177 and make `val` a method you can call on an object to get the dimenesion vals, as it isn't ambiguous.

**Comment by Datseris** [comment]
What is `DimDataset`...?

I couldn't find it here: https://rafaqz.github.io/DimensionalData.jl/dev/search/?q=DimDataset

**Comment by rafaqz** [comment]
See #173. Requested way back in #80.
