### ISSUE TITLE
Does `val` supports `val(A::AbstractDimArray, dims::Tuple)  => Tuple` now?

### ISSUE THREAD

**Issue by singularitti** [rafaqz/DimensionalData.jl#177]
In the doc it says it does, but I didn't see it in its `methods`:

```julia
julia> methods(val)
# 8 methods for generic function "val":
[1] val(dims_::Tuple{})
 @ DimensionalData ~/.julia/packages/DimensionalData/IHaNW/src/dimension.jl:182
[2] val(span::Regular)
 @ DimensionalData ~/.julia/packages/DimensionalData/IHaNW/src/mode.jl:229
[3] val(dim::AnonDim)
 @ DimensionalData ~/.julia/packages/DimensionalData/IHaNW/src/dimension.jl:283
[4] val(dim::Dimension)
 @ DimensionalData ~/.julia/packages/DimensionalData/IHaNW/src/dimension.jl:146
[5] val(dims_::Tuple{var"#s39",Vararg{Dimension,N} where N} where var"#s39"<:Dimension)
 @ DimensionalData ~/.julia/packages/DimensionalData/IHaNW/src/dimension.jl:181
[6] val(dims_::Tuple{var"#s39",Vararg{Dimension,N} where N} where var"#s39"<:Dimension, lookup)
 @ DimensionalData ~/.julia/packages/DimensionalData/IHaNW/src/dimension.jl:183
[7] val(sel::Where)
 @ DimensionalData ~/.julia/packages/DimensionalData/IHaNW/src/selector.jl:195
[8] val(sel::Selector)
 @ DimensionalData ~/.julia/packages/DimensionalData/IHaNW/src/selector.jl:19
```

**Comment by rafaqz** [comment]
Yeah seems I missed including `val` in the [list](https://github.com/rafaqz/DimensionalData.jl/blob/master/src/array.jl#L56-L59) of methods. These functions are all generated in an `@eval` loop there's no actual code for them individually.

If you are looking for the dimension index you can use `index` instead of val, which is included in the list but which only works when it contains a vector or `Val` tuple (to guarantee what is returned is indexable). But I'll add `val`.

**Comment by rafaqz** [comment]
There may have been a reason for this actually... calling `val` on the array seems like it should return the array parent, where `index` clearly means the dimension index. These methods need more thought.

`val` refers to the value of a `Dimension` object whatever it contains (which can be anything - we use it in `set` to set every other field, and for `getindex` etc.

`index` refers to the index of the `Dimension` when it is specifically used to hold that in a `dims` field. (It might be good to wrap `Val(sometuple)` in our own type so that the whole thing is returned and is directly indexable, instead of needing to be unwrapped in `index`. That would be cleaner.)

**Comment by rafaqz** [comment]
The docs are fixed on master. Thanks for catching that!
