### ISSUE TITLE
Reverse indices do something funny

### ISSUE THREAD

**Issue by mauro3** [rafaqz/DimensionalData.jl#232]
Consider:
```
using Plots, DimensionalData
heatmap(DimArray(rand(10,10), (X,Y))[1:10,10:-1:1]) # has stripes with y-axis 2:9
heatmap(DimArray(rand(10,10), (X,Y)).data[1:10,10:-1:1]) # ok 
heatmap(DimArray(rand(10,10), (X,Y))[1:10,10:-1:1].data) # ok too
```
Loks like an issue with the plotting?

maybe related: #190

**Comment by rafaqz** [comment]
Currently a reverse or out-of-order array index is undefined behaviour. Some plots backends cant even plot with an axis in reverse - and those are different plots - the first plots axis values as well. But its possible this particularbehaviour could be better.
Generally when you use a reversed range for indexing you reverse the array without DD knowing, so `searchsortedfirst` will be broken if you tried to use `Near` or `Between`.

**Comment by mauro3** [comment]
So, the recommended way to do this is to use `reverse`?

**Comment by rafaqz** [comment]
Just to be clearer, what DD plots in your first example is actually this:

```julia
heatmap(10:-1:1, 1:10, DimArray(rand(10,10), (X,Y))[1:10,10:-1:1].data)
```

Which has the same problem you experience plotting the `DimArray` directly. GR plots a completely empty plot, pyplot plots the bars. So this is really a plots backend bug - I don't know why the axis can't be backwards, it's a perfectly reasonable thing to want.

**Comment by rafaqz** [comment]
using `reverse` wont have the outcome you want, because the index would still be in reverse and can't plot that way. The behaviour is actually to just still plot the right way. 

For spatial data often the data is backwards on one axis and reversing it eagerly is expensive, so we just reverse it at the point of plotting. But it generally has a "right way" to be plotted, no matter the underlying representation.

Maybe in this case - where you don't have an index, none of this should apply - it should just plot without the axes. But usually you want the axes to plot. I don't know how to handle it honestly, especially seeing that the plot backends wont plot the reversed axis anyway.

**Comment by rafaqz** [comment]
For now I'll fix `NoIndex()` behaviour so that none of this applies - it really shouldn't.

But it's not easy dealing with order when you have and index that does matter (`Sampled` mode) and both plotting and `searchsortedfirst` care about order, and the index or the plot can be backwards.
