### ISSUE TITLE
`checkaxis` seems to check against the axes of the underlying `.data` instead of `data()`?

### ISSUE THREAD

**Issue by ali-ramadhan** [rafaqz/DimensionalData.jl#265]
Apologies if I'm using DimensionalData.jl incorrectly (so the title might be wrong) but I'm trying to use an `OffsetArray` inside a `DimArray` where I want operations to only act on some interior portion of the `OffsetArray` (I want to ignore rectangular "halo" regions at the edges of the `OffsetArray`).

Here's a minimal example I came up with

```julia
using OffsetArrays
using DimensionalData

import DimensionalData

OffsetAbstractDimMatrix = AbstractDimArray{T, 2, D, <:OffsetArray} where {T, D}

function DimensionalData.data(da::OffsetAbstractDimMatrix)
    o1, o2 = offsets = da.data.offsets # offsets are negative.
    n1, n2 = size(da.data)
    return view(da.data, 1:n1+o1-1, 1:n2+o2-1)
end

function DimensionalData.val(dim::Dimension{<:OffsetArray})
    offset = first(dim.val.offsets) # offsets are negative.
    n = length(dim.val)
    return view(dim.val, 1:n+offset-1)
end

xs = ts = OffsetArray(1:10, -1)
data = OffsetArray(randn(10, 10), -1, -1)
da = DimArray(data, (X(xs), Ti(ts)))
```

but construction seems to fail due to `checkaxis`:

```
ERROR: LoadError: DimensionMismatch("axes of X of Base.OneTo(8) do not match array axis of OffsetArrays.IdOffsetRange(0:9)")
Stacktrace:
 [1] checkaxis at /home/alir/.julia/packages/DimensionalData/BLGYA/src/dimension.jl:498 [inlined]
 [2] _formatdims(::OffsetArrays.IdOffsetRange{Int64,Base.OneTo{Int64}}, ::X{OffsetArray{Int64,1,UnitRange{Int64}},AutoMode{AutoOrder},NoMetadata}) at /home/alir/.julia/packages/DimensionalData/BLGYA/src/dimension.jl:481
 [3] map at ./tuple.jl:177 [inlined]
 [4] _formatdims at /home/alir/.julia/packages/DimensionalData/BLGYA/src/dimension.jl:476 [inlined]
 [5] formatdims at /home/alir/.julia/packages/DimensionalData/BLGYA/src/dimension.jl:474 [inlined]
 [6] formatdims at /home/alir/.julia/packages/DimensionalData/BLGYA/src/dimension.jl:470 [inlined]
 [7] DimArray(::OffsetArray{Float64,2,Array{Float64,2}}, ::Tuple{X{OffsetArray{Int64,1,UnitRange{Int64}},AutoMode{AutoOrder},NoMetadata},Ti{OffsetArray{Int64,1,UnitRange{Int64}},AutoMode{AutoOrder},NoMetadata}}, ::NoName; refdims::Tuple{}, metadata::NoMetadata) at /home/alir/.julia/packages/DimensionalData/BLGYA/src/array.jl:181
 [8] DimArray at /home/alir/.julia/packages/DimensionalData/BLGYA/src/array.jl:181 [inlined] (repeats 2 times)
 [9] top-level scope at /home/alir/Oceananigans.jl/test/offset_dim_array.jl:26
 [10] include(::String) at ./client.jl:457
 [11] top-level scope at REPL[25]:1
in expression starting at /home/alir/Oceananigans.jl/test/offset_dim_array.jl:26
```

It seems that it's comparing `Base.OneTo(8)` to `OffsetArrays.IdOffsetRange(0:9)` but shouldn't it be comparing it to the `axes` of `DimensionalData.data(da)` which should be `(Base.OneTo(8), Base.OneTo(8))`?

**Comment by rafaqz** [comment]
Hmm no that wont really work :)

Regular offset arrays do work as long as you use matching offset arrays for the dimensions:
https://github.com/rafaqz/DimensionalData.jl/blob/master/test/array.jl#L58-L76

But `formatdims` that is causing the error here is actually called before any `DimArray` is constructed, simply on the array object and the dimensions, so your methods have no effect:
https://github.com/rafaqz/DimensionalData.jl/blob/master/src/array.jl#L181

`formatdims` is to verify that the dims and array match and to finish constructing the dimensions and filling any missing mode fields. The main rule is that the dimension axes have to match the array axes, or everything gets weird. 


As for the halo, what I would do is define your own array wrapper that returns the inner `size`, `axes`, `length` etc, smaller than the contained `OffsetArray`. Then the halo is hidden from other methods and acts like a normal array, but `getindex` etc may still index into the halo when you need that.

This is exactly how DynamicGrids.jl does padding for convolutions/neighborhood mapping. The grid size is presented as a regular array with normal axes, but it wraps a larger `OffsetArray` so we don't have to bounds check.

You can set `parent` to be a `view` over the `OffsetArray` so that broadcast works too, and if you know the size at compile time it can be a `SizedArray` wrapping the view and it will remove all the overhead, ending up faster than regular broadcasting:

https://github.com/cesaraustralia/DynamicGrids.jl/blob/master/src/grid.jl#L205

Unfortunately the padded grids are really too complicated to use as an example for much else.

But if you use an array like that you can just use regular axes in the dims here and everything should work.

**Comment by ali-ramadhan** [comment]
Thank you for the thorough reply and explanation!

I think you're right I should probably define an array wrapper for this. I'll give it a try and should be able to build something up this way!

Closing this issue since it's not a bug.

**Comment by ali-ramadhan** [comment]
Thanks again for the help! Was able to prototype something that I can build on.

```julia
using OffsetArrays
using DimensionalData

struct HaloedArray{T, N, D, H} <: AbstractArray{T, N}
    data :: D
    halo :: H

    function HaloedArray(data::D, halo::H) where {D, H}
        return new{eltype(data), ndims(data), D, H}(data, halo)
    end
end

@inline Base.size(ha::HaloedArray) = size(ha.data) .- 2 .* ha.halo
@inline Base.getindex(ha::HaloedArray, inds...) = getindex(ha.data, inds...)
@inline Base.setindex!(ha::HaloedArray, inds...) = setindex!(ha.data, inds...)
@inline Base.parent(ha::HaloedArray) = ha.data.parent

function Base.showarg(io::IO, ha::HaloedArray, toplevel)
    print(io, "HaloedArray(")
    Base.showarg(io, parent(ha), false)
    print(io, ')')
    print(io, " with halos of size $(ha.halo)")
end

function HaloedArray(data; halo)
    offsets = Tuple([-h for h in halo])
    offset_data = OffsetArray(data, offsets)
    return HaloedArray(offset_data, halo)
end
```

```julia
julia> ha = HaloedArray(randn(6, 6), halo=(2, 2))
2×2 HaloedArray(::Matrix{Float64}) with halos of size (2, 2):
  1.15802   -0.54212
 -0.110787  -0.824397

julia> hda = DimArray(ha, (X(1:2), Ti(1:2)))
2×2 DimArray{Float64,2} with dimensions: 
  X: 1:2 (Sampled - Ordered Regular Points)
  Ti (Time): 1:2 (Sampled - Ordered Regular Points)
  1.15802   -0.54212
 -0.110787  -0.824397

julia> mean(hda, dims=X)
1×2 DimArray{Float64,2} with dimensions: 
  X: Int64[2] (Sampled - Ordered Regular Points)
  Ti (Time): 1:2 (Sampled - Ordered Regular Points)
 0.523614  -0.683258
```
