### ISSUE TITLE
SplitApplyCombine

### ISSUE THREAD

**Issue by rafaqz** [rafaqz/DimensionalData.jl#3]
It would be good to support SplitApplyCombine.jl or something similar, so that complex manipulations could be applied along dimensions in a structured way, say getting mean daily values from hourly values over some timespan.

**Comment by ivirshup** [comment]
I've got a very [draft-y working example of this](https://gist.github.com/ivirshup/148705a8870b1243375e51e2e5322d01). It's stopped being consistently type stable since I started trying to allow grouping over multiple dimensions, but I'm going to blame inference being temperamental.

A few open questions:

* How much should can/ should the structure of splitapplycombine or similar libraries be used?
* Should combining be implicit (like pandas) or explicit (like `SplitApplyCombine.jl`)? Implicit can give better performance by preallocating outputs, but explicit is more flexible.
* How hard would it be to broadcast over the groupings?

**Comment by rafaqz** [comment]
Looks greatp. 

Lets leverage external packages as much as possible? Minimising the syntax that we define here is one on my goals.

So maybe we can first support the SplitApplyCombine.jl explicit method, and implement implicit if we really need it? Im not totally clear on the differences as I don't use Pandas.

For type stability I tend to use recursive methods - it avoids being exposed to performance loss due to compiler changes. I havent tried it but the `while` loop looks like it could be a problem with multiple dim types.

**Comment by ivirshup** [comment]
I'll try and figure out how much their syntax can be matched, but their code is largely based around one dimensional iterators. In theory this shouldn't be so bad, but code seemed to drop a lot in performance when I used code like `eachslice` or `reduce(selectdim, dims, A)`.

--------------

The main difference between explicit and implicit is if a `Dictionaries.Dictionary` is returned, or a `DimensionalArray`. Explicit is taking the mean over your groups and getting a dictionary mapping group names to means back. I like the consistency of a DimensionalArray being returned, but it's easier to return a Dictionary. Explicit raises the problem of implementing combining methods, and figuring out what the new dimensions should be.

Also, this is basically the implementation for the explicit version, at least for the apply step:

```julia
(v->mean(expr[Obs(v)], dims=Obs)).(groupfind(groups::CategoricalArray))
```

---------

A big change in typing ability came from having multiple dim types, which are `Tuple{UnionAll...}` if they aren't instances. Then there was inference sometimes working well with `map`, sometimes working well with `broadcast`.

The loop is a problem, but I think it's due to the variable used outside the loop at the moment. I'm not sure how else to allocate the output without peeking at the first result.

**Comment by rafaqz** [comment]
Dimensional eachslice should be type stable? regular eachslice isn't. The implementation here is much faster than the base implementation.

My rules of thumb for type stability with tuples of mixed types: never use broadcast or loops. Recursion is the only way. So `map` etc or hand rolled.

Returning a `DimensionalArray` does seem better to me too...

**Comment by ivirshup** [comment]
It's type stable, `mean.(eachslice(da, dims=X))` is just slower than `mean(da, dims=X)`.

On that topic of type stability, I want to get the difference of the types which are in two tuples. How do I filter a tuple in a type stable way?

**Comment by rafaqz** [comment]
Use manual recursive methods or `map`, which is recursive underneath. Just copy something in primitives.jl
