### ISSUE TITLE
Reading NetCDF

### ISSUE THREAD

**Issue by tomchor** [rafaqz/DimensionalData.jl#431]
I couldn't find any functionality for reading NetCDF files. Is there any at this point? Or would one need to construct a `dimarray` manually after reading the NetCDF? If it's the latter, are there plans to add netcdf functionality?

Thanks!

**Comment by sethaxen** [comment]
I'm also interested in this. I have a package [InferenceObjectsNetCDF](https://inferenceobjects.julia.arviz.org/stable/subpackages/inferenceobjectsnetcdf/) that loads a netCDF file containing a hierarchy of groups into a corresponding hierarchy of `AbstractDimStack`s, but something more general would be nice.

**Comment by rafaqz** [comment]
These should mostly just work as you expect :
```julia
Raster("my.nc"; name=:varname)
RasterStack("my.nc")
```

**Comment by tomchor** [comment]
@rafaqz it looks like these packages together can be really powerful! I've been looking for something like this for a while in Julia and completely missed this because I just wasn't aware that it could do these things. Judging by the amount of people looking to find packages to replace the functionality of `python.xarray` in Julia, I bet there a dozens more like me.

Would you be interested in writing a quick tutorial for the docs explaining how to read NetCDF data and subsequently plot it? I could help you out.

(In particular in would be amazing to show how to make animations using these packages!)

**Comment by sethaxen** [comment]
> @sethaxen Rasters.jl will load things like the bounds variables properly of they exist. `RasterStack` is an `AbstractDimStack`.

I've seen `RasterStack` before. Rasters is quite a large package though (takes 4.4s to load on my machine compared to InferenceObjectsNetCDF, which takes just 0.5s) and has a lot of functionality I wouldn't need, so it wouldn't be a suitable dependency for me. But wrapping a netCDF as an `AbstractDimStack` seems like something that would be generally useful apart from rasters functionality.

> But it always makes one stack per file.

Yeah this is a show-stopper for me, since we almost always have more than one stack. What if `RasterStack` could take an opened `NCDataset` containing a single group as an argument instead?

**Comment by rafaqz** [comment]
@tomchor Rasters.jl has a lot of docs for this - I wasn't clear, but that's the package that builds on DimensionalData.jl that reads netcdf via NCDatasets.jl

Specifically docs for loading netcdf:
https://rafaqz.github.io/Rasters.jl/stable/#Loading-and-plotting-data

Read through those and have a go.

DimensionalData.jl has the abstractions required to handle a lot of what netcdfs can contain, because it was written specifically to facilitate that. But it's also is a light-weight backend for multiple packages, and used by people who don't use netcdf at all. So we can't support netcdf here directly.

@sethaxen what we could do to a void the ArchGDAL/CoordinateTransformations etc dependencies of Rasters.jl is make a new `DimensionalDataNetCDF.jl` and include any shared functionality there. Someone else would have to do that but I can review PRs etc. I'm really pushing the limits of the number of packages I can maintain and my interest in NetCDF is mostly limited to the CF standards -  e.g. I have never used a file that needed multiple `DimStack`s to represent it.

Things I need from NetCDF that are in either half done or not yet written are a `LookupArray` for matrix dimension variables, DiskArrays.jl integration, and a CF projection parser.

**Comment by tomchor** [comment]
Thanks @rafaqz. I was looking for the plotting recipes/tutorial before you had told me that Rasters.jl existed. I'm trying it out indeed I learned a lot from the plotting examples there.

I'm closing this since this answers my question.
