### ISSUE TITLE
Add comparison to NamedArrays

### ISSUE THREAD

**Issue by diegozea** [rafaqz/DimensionalData.jl#44]
Hello,
I am using the [NamedArrays.jl](https://github.com/davidavdav/NamedArrays.jl) package, and I would like to know how this package compares to it.
Best regards,

**Comment by rafaqz** [comment]
That kind of documentation is the main thing lacking here at this point, as things have only recently settled.

But I'll try the differences with NamedArays, although I don't really use it. This package is made to be extensible, and focussed on the dimension and many kinds of index and metadata for it, rather than just named categories. So dims are types like `X()` that can hold an index `["a", "b", "c"]` etc. Rather than strings/symbols in dicts as in named arrays.

```
n = NamedArray([1 3; 2 4], ( ["a", "b"], ["c", "d"] ), ("Rows", "Cols"))
using DimensionalData
using DimensionalData: X, Y
A = DimensionalArray([1 3; 2 4], (X(["a", "b"]), Y(["c", "d"])))
```

You could index with numbers, ignoring the order 
```julia
julia> A[Y(2), X(1)]
3
```

Unlike NamedArrays, this is a zero runtime cost operation.

The syntax has selector types like `At()`, `Near()` and `Between` index based on some lookup grid, which you can extend or customise as well. So you could select with category names:

```julia
julia> A[Y(At("d")), X(Between("a", "b"))]
2-element DimensionalArray{Int64,1,Tuple{X{Array{String,1},CategoricalGrid{Ordered{Forward,Forward,Forward}},Nothing}},Tuple{Y{String,CategoricalGrid{Ordered{Forward,Forward,Forward}},Nothing}},Array{Int64,1}}:
 3
 4
```
Or if you know the order:
```julia
julia> A[At("a"), At("d")]
3
```

But you can also do:

```julia
A[X(At(["a"])), Y(Near(23.75))]
```
Where X has a categorical grid and Y has some numeric index that maps to the array.

This package was made to work primarily with spatial data - so it can handle step size and bounds updating when you subset or use some reducing function. It also provides plot recipes and tracks some changes that are useful to plot. I think it will remain `<: AbstractDimensionalArray` through a lot more base methods than NamedArrays will remain a `NamedArray`, but I'm not sure.

I am guessing that most of NamedArrays is like the `CategoricalGrid` grid type in DimensionalData. Which NamedArrays is probably better at in many ways. But DimensionalData will probably have better performance for a lot of things, and useful for or customisable to a wider range of applications. 

It could be good to work on any features NamedArrays has that DimensionalData lacks in its `CategoricalGrid` behaviour.
