### ISSUE TITLE
samples vs means / implementing a histogram

### ISSUE THREAD

**Issue by jw3126** [rafaqz/DimensionalData.jl#45]
## Motivation
Usually I have data, that is localized in some dimensions and represents averages in other dimensions. For instance there could be a time axis and a position axis and each value in the data matrix corresponds to a precise timepoint, but is an average over a space region.
I think `DimensionalData`  deals very well with the former very well (data are point values), but for me it seems to not work so well for the latter (data are bin averages).

Lets reduce this example a bit to the case of representaing a 1d histogram. The histogram has `n` bins, that means `n` data values and `n+1` walls that represent the bin boundary.

One operation that I would like to do frequently is to decide for an arbitrary position to which bin it belongs. This will require doing something like `searchsorted(walls, x)`. So we need a `Dimension` that remembers the `n+1` walls. 

As far as I can see, there is no such thing build in?

## Minimal implementation
```julia
using DimensionalData
using DimensionalData: X
import DimensionalData: sel2indices

struct Bins{W}
    walls::W # assumed to be sorted
end
struct Interval{T}
    left::T
    right::T
end
Base.eltype(::Type{Bins{W}}) where {W} = Interval{eltype{W}}
Base.length(w::Bins) = length(w.walls) - 1
Base.getindex(w::Bins, i::Integer) = Interval(w.walls[i], w.walls[i+1])

struct BinAround{T} <: Selector{T} # shorter name BinOf? Or even pack this into At?
    val::T
end

function sel2indices(grid, dim, sel::BinAround)
    bins = dim.val::Bins
    # TODO more correct edge cases,
    # also which bin to select in case val sits on a boundary?
    # Either BinAround or Bins needs to contain a closed left/right flag.
    index = searchsortedlast(bins.walls, sel.val)
end

arr = DimensionalArray(10:10:90, (X(Bins(1:10)),))
arr[BinAround(2.9)]
```
## Questions
Am I correct, that this kind of functionality is currently not in `DimensionalData.jl`? Does it make sense to add it here? Is the above implementation strategy sane? If so I am happy to polish this and make a PR.

**Comment by rafaqz** [comment]
That's an interesting good use case. I don't think you can quite get what you want currently. Maybe we can just call the selector `Bin`?

[grids.jl](buthttps://github.com/rafaqz/DimensionalData.jl/blob/master/src/grid.jl) has the traits in place to deal with things like this, although you may need another grid type to get exactly what you want, I'm not sure yet.


`RegularGrid` and `BoundedGrid` both track dimension bounds, which may help here? `RegularGrid` has a step value (like a range but it holds for LinRange length 1 and other corner cases) which gives you the outer bounds. But all bins must be the same size.

Bounded grid doesn't have a fixed step size, so it tracks the bounds on every getindex. Bins could be different sizes with this grid.

The exact position of the bounds is also determined by wether the grid locus is `Start`, `Center` or `End` of the cell. Bounds are retrieved for arrays or individual dims with the `bounds` method.


This functionality is all fairly new and may contain some bugs and things that don't make sense. It also isn't settled what grid types are required to cover all the use cases people will need, so feel free to play with adding or changing what I have done.

**Comment by jw3126** [comment]
I do not fully understand your suggestion. What would the example
```julia
arr = DimensionalArray(10:10:90, (X(Bins(1:10)),))
arr[BinAround(2.9)]
```
look like?

Would your suggestion at some point involve splitting walls into e.g. `walls[begin]` and `walls[begin+1:end]`? Because that would make me cry.

**Comment by rafaqz** [comment]
Ok I'll have to put an example together. There wouldn't be `Bins` vector at all, just the standard existing vector of cell start/center/end points that you use `searchsortedx` over, and a bounds check to make sure the value is actually inside the first/last bin. Which we can easily do because `bounds` are known. Bins are just the span between each index, or around `Center` locus indices.

A lot of code above isn't needed to write a `Bin` selector given what already exists. But extra code will be needed to work with reverse indexes and with sampling positions not at the start of the bin, but at the center or end of it.

**Comment by jw3126** [comment]
Thanks! In the example, how to add the information that the right end wall is at `10`?
Can you explain a bit, what are the responsibility of the grid trait and what not?

I really don't like that we have to chop off the beginning or end of walls. To me this seems unnatural, cumbersome and error prone.

Also it seems to me that the existing grids really are about either categorical or point data and it feels hacky to abuse the point data grids like this.

But I understand that while to me my use case is the most important thing in the world, it might look like exotic nonsense to others.

Is `X(some_wrapper(walls))` negotiable? Possibly with a new grid type?

**Comment by rafaqz** [comment]
`bounds(dim)` returns `(1, 10)` :)

The bounds check just makes sure the value is inside the whole dimension, after which we can be sure `searchsortedlast` will place the value in an actual bin - we don't have to worry about the last right wall as it has already been checked.

The grids aren't necessarily about point data either. For most of my uses cases (spatial data) they are mean values in both time and space. There is also a trait `SingleSample` and `MultiSample` that can help identify this if we need to. `MultiSample` takes a type parameter which can be a method like `mean`, `sum` etc. But this hasn't really been used or fully thought through yet.

And what do you mean by chop off the begging or end of walls? Where does that happen? I can't see the practical difference between your code and mine to be honest.

**Comment by jw3126** [comment]
It might be that I am just understanding something wrong and there is no need to chop walls. Let me ask, how would the example look like if `walls = sort(randn(10))`? My impression was:
```julia
arr = DimensionalArray(10:10:90, (X(walls[1:9]),))
```
? But then how does the array know about walls[10]`

**Comment by rafaqz** [comment]
Ok if you pass in an array instead of a range you have to do a bit more work as the step size isn't known, or it's variable.

Either the array is basically a glorified range and the step size is the same, in which case you use `RegularGrid` and manually set the step size to what you want. Otherwise, with mixed step sizes you need to use BoundedArray and set the `bounds` keyword to `(firstwall, lastwall)`. After that, the bounds are updated automatically when you subset with `view` or `getindex`.

So:
```
arr = DimensionalArray(10:10:90, (X(walls[1:9]; grid=BoundedGrid(;bounds=(firstwall, lastwall)),))
```

This stuff all needs better documentation, but I'm not totally settled on the implementation yet. We can also work on some shorthand ways to set `bounds` and `step` more easily. Ie the X constructor should just take a `bounds` keyword that works out the above itself if you actually set it.

**Comment by jw3126** [comment]
To me representing averages over spatial segments is in a way closer to a categorical dim, where the labels are intervals, then to a data point grid. If you view it like this, then there is no problem with 10 walls, as there are only 9 intervals. Chopping the walls, arbitrarily choosing a representing space point at start/mid/end of interval. All this is man made bureaucracy. 

Why not add a `BinGrid` on par with the categorical and point grids? It will assume that `get_walls` is defined on `dim.val` and enable the `Bin` selector. This way `Intervals` and `Bins` types can live in user space and don't have to be part of `DimensionalData.jl` if you don't like to have them here.

**Comment by rafaqz** [comment]
Categories are not intervals, just groups. Intervals are what `RegularGrid` and `BoundedGrid` are already for. That's why I'm struggling to see the need for `BinGrid`.

The problem with using 10 walls is purely technical. When a grid is subset, the same indices subset the dims as subset the array. So you will lose the last wall anyway. A lot of other methods like `aggregate` in GeoData (which will move here eventually) and `cat` rely on dims and grid axes being the same size so they can be joined/subsetted correctly. Special casing this will be a mess to maintain.

Pleas understand that there is a whole stack of useful code here to work with, so lets do this the easy way and keep things DRY.

`Bin` will work _exactly_ as you want. Just using different code under the hood. That is as much as I can do. We have to limit the bloat of this package because there are so many competing use cases.

**Comment by jw3126** [comment]
> 
> 
> Categories are not intervals, just groups.

I thought categories would allow arbitrary labels like `X(["foo", "bar"])` or `X([MyLabelObject1, MyLabelObject2])`?
>  Intervals are what `RegularGrid` and `BoundedGrid` are already for. They are not point grids! They can be either. That's why I'm struggling to see the need for `BinGrid`.

But they force you in the end to decide for each data value to map it to a point (begin/mid/end) no?
So it is not intervals, but can emulate intervals with extra structure.

> The problem with using 10 walls is purely technical. When a grid is subset, the same indices subset the dims as subset the array. So you will lose the last wall anyway. A lot of other methods like `aggregate` in GeoData (which will move here eventually) and `cat` rely on dims and grid axes being the same size so they can be joined/subsetted correctly. Special casing this will be a mess to maintain.
> 
There is no such special casing with my suggestion. `Bins(1:10)` is an iterator (or `AbstractVector`) with 9 Interval elements. The fact that these intervals are defined by 10 walls is only a concern to the `Bin` selector, the rest of the code base does not see the walls. It only sees an iterator with 9 elements.
I think it will be easy to maintain.

> Pleas understand that there is a whole stack of useful code here to work with, so lets do this the easy way and keep things DRY.
> 

Sure I understand that there is a lot of useful code here, otherwise I would not try to use this package. I guess we both try do do it the easy way, it's just that we do currently not agree what the easy way is.
I do agree, adding this would make the code base slightly less DRY. But hopefully only temporarily.

> `Bin` will work _exactly_ as you want. Just using different code under the hood. That is as much as I can do. We have to limit the bloat of this package because there are so many competing use cases.

Ah ok no it does not work exactly as I want. Its not that I am worried about a low level implementation detail that is invisible to the user. What I want on a high level is the following:
My data consists of say a vector of measured values and a vector of bin walls. I want to encapsulate this in a single convenient object.
With your suggestion walls is not encapsulated, in the data array. I would have to pass it seperatly or reconstruct it (which causes an allocation) etc.
Also we would have to fix a convention about on which side to chop the wall and always remember it etc.

**Comment by jw3126** [comment]
Also thanks a lot for your patience and feedback in this discussion.

**Comment by rafaqz** [comment]
A questions:

What do you mean by chopping the wall? I think half the problem here is we are talking across each other with entirely different terms for the same things. I don't see what chopping has to happen...

Some answers:

> I thought categories would allow arbitrary labels like X(["foo", "bar"]) or X([MyLabelObject1, MyLabelObject2])?

Categories absolutely can have arbitrary labels. What they do not have is _width_. 

> But they force you in the end to decide for each data value to map it to a point (begin/mid/end) no?
So it is not intervals, but can emulate intervals with extra structure.

Intervals do not force you to map to a point. You have this inside out. Intervals force you to specify some anchor point that determines the range covered by the interval.  You don't need to specify both sides. You just specify that the index references one side of the interval (with `Start`/`End`) or the center of it with `Center`. The far wall is determined by the step size or the next point location. The default is `Start` but `Center` is also quite common in the wild when you have equal step sizes. This is how basically all spatial data storage works.

> There is no such special casing with my suggestion. Bins(1:10) is an iterator (or AbstractVector) with 9 Interval elements. 

An iterator over an Array of _10 elements_. This array/iterator combo needs to be able to be subset/resampled/concatenated/reduced/sliced etc like every other grid type to be part of this package, and will need special casing everywhere those things happen to handle the last wall. `RegularGrid` and `BoundedGrid` and `bounds` already work through all these transformations, and making it so was a massive amount of work and thought that I do not wish to repeat. Please work with me to use them.

> I guess we both try do do it the easy way, it's just that we do currently not agree what the easy way is.

What I mean by simple solution is who's adds the most custom code: mine adds _far_ less. You are not seeing the amount of code that will be required to handle your walls array everywhere else.

> Ah ok no it does not work exactly as I want. Its not that I am worried about a low level implementation detail that is invisible to the user. What I want on a high level is the following:

By exactly what you want, I mean the syntax and output of the `Bin` selector will be identical to your solution. 

Your input data may need to be wrangled, but really not much by the look of it. We can also work on the syntax, as I have said. To expect me to maintain so much more code so you can keep your exact workflow is asking a bit much tbh. Please make some compromises here.

**Comment by jw3126** [comment]
> 
> 
> A questions:
> 
> What do you mean by chopping the wall? I think half the problem here is we are talking across each other with entirely different terms for the same things. I don't see what chopping has to happen...

```julia
walls = sort(randn(10))
# In the next line the last wall is chopped off
dim = X(walls[1:9]; grid=BoundedGrid(;bounds=(firstwall, lastwall))
# the next object does not have a reference to `walls` anymore only to its pieces
DimensionalData(randn(9), (dim,)) 
```
> Categories absolutely can have arbitrary labels. What they do not have is _width_.

Sure. I did not say that `Bins` should be a `CategoricalGrid`. Just that it resembles it in that elements are not coordinates, but something else (Intervals).

> Intervals do not force you to map to a point. You have this inside out. Intervals force you to specify some anchor point that determines the range covered by the interval. You don't need to specify both sides. You just specify that the anchor point/index references one side of the interval (with `Start`/`End`) or the center of it with `Center`. The far wall is determined by the step size or the next index location. The default is `Start` but `Center` is also quite common in the wild when you have equal step sizes. This is how basically all spatial data storage works.
> 

Yeah I understand that. The anchor point style (`Start`/`Center`/`End`) is a choice that is not present in the initial problem, its an artifact of the proposed solution.
Also I suspect that a lot of functions will have surprising behaviour from bins viewpoint. For instance (assuming the default `Start`) from the bins viewpoint the correct `Near` implementation would be to always search the closest point on the left of searching the closest point on any side.

> To expect me to maintain so much more code so you can keep your exact workflow is asking a bit much tbh.

Yes sure I understand that. I did not expect this to need so much code in the beginning.

> Please make some compromises here.

So I could live with an implementation that internally e.g. chooses an anchor point if that choice is invisible from the outside.

But as noted above I think it will be visible from the outside.  The behaviour will look buggy from the bins point of view.
Also I would really like to have a reference to the original `walls` from the `DimensionalData` object. 

I guess these are both not really possible? Thanks for creating this package anyway, I like it even if it does not support bins in the way I wish.

**Comment by rafaqz** [comment]
You don't have to choose. `Start` is the default used for basically everything. That's how it already works. You are complaining about non-existent problems. I've also explained the changes that need to happen to `Near`. Please actually read what I am writing to help you.

You need to come to terms with the fact that the result will be identical and your method will break everything else in this package. Your gripes are tiny compared to the problems your solution causes.

**Comment by rafaqz** [comment]
```julia
dim = X(walls[1:9]; grid=BoundedGrid(;bounds=(firstwall, lastwall))
# the next object does not have a reference to `walls` anymore only to its pieces
DimensionalData(randn(9), (dim,))
```

What do you need the walls for lol the Bin selector you are asking for will work anyway. I am hoestly so confused by this thread.

**Comment by jw3126** [comment]
> 
> You don't have to choose. `Start` is the default used for basically everything. That's how it already works. You are complaining about non-existent problems. I've also explained the changes that need to happen to `Near`. Please actually read what I am writing to help you.

Sorry. I actually read it, but did not see the problem at that point and then forgot about it.

> 
> You need to come to terms with the fact that the result will be identical

Ok I try. So you expect that after fixing `Near` and `Between` all functions will have correct behaviour from the bins picture?

> What do you need the walls for lol

For instance I often need to compute the bin volume. One goal for me is to encapsulate that data I have faithfully and without "reconstruction overhead" in one object. The walls are part of that.

> I am honestly so confused by this thread.

Sorry! Me too but it is getting better. I think it is mostly that we use a different language and have very different opinon on the importance of walls 😃.
