### ISSUE TITLE
Docs build issues

### ISSUE THREAD

**Issue by asinghvi17** [rafaqz/DimensionalData.jl#648]
- Warning: undefined binding 'DimensionalData.DimColumn' in `@docs` block in src/api/reference.md:46-50
- Warning: no doc found for reference '[`Dimension`](@ref)' in src/object_modification.md.
- Warning: no doc found for reference '[`Selector`](@ref)' in src/object_modification.md.
- Warning: no doc found for reference '[`LookupArray`](@ref)' in src/object_modification.md.
- Warning: no doc found for reference '[`lookup`](@ref)' in src/api/dimensions.md.
- Warning: no doc found for reference '[`@dim`](@ref)' in src/api/dimensions.md.
- Warning: no doc found for reference '[`@dim`](@ref)' in src/api/dimensions.md.
- Warning: no doc found for reference '[`Selector`](@ref)' in src/selectors.md.
- and so on...
- Links being rendered inside the anchor text breaking anchoring (this is a DocumenterVitepress bug)

**Comment by rafaqz** [comment]
Lots of those docs do exist tho... maybe in modules

**Comment by lazarusA** [comment]
maybe we should include something here https://github.com/rafaqz/DimensionalData.jl/blob/e65dcf95db6f75b39f0e0d892ab7c68b240bcd94/docs/make.jl#L4  like this 
```
DocMeta.setdocmeta!(DimensionalData, :DocTestSetup, :(using DimensionalData.Modules); recursive=true)
```
see https://documenter.juliadocs.org/stable/lib/public/#Documenter.DocMeta.setdocmeta!.

so that the whole thing is available everywhere. However, I don't like it that much because then we are not forced to specify from where we are using functions in the examples. But it's necessary when using references in the text.

**Comment by rafaqz** [comment]
Fixed
