### ISSUE TITLE
Would it make sense to add support for defining dimensions with a symbol -OR- string?

### ISSUE THREAD

**Issue by alex-s-gardner** [rafaqz/DimensionalData.jl#797]
Maybe it's just me but I find it slightly restrictive that Dim does not accept a `string` in the definition of dimension. I'm guessing that you've already thought about this and have a good reason for not supporting it but thought I'd mention it. 

if would be nice if 
```
Dim{"dim1"}(1:3)
```
was equivalent to 
```
Dim{:dim1}(1:3)
```

**Comment by rafaqz** [comment]
Can't we just use Symbols? It complicates things a lot to allow both everywhere, it's weird to switch parameter types like that in a constructor, and it's just slower to use strings anyway. We can't even use strings for DimArray names because they just need to be Symbol sooner or later to use in DimStack and DimTable.

I know strings for things like this is very Python fruendly. I used Ruby more than Python back in the day so Symbols seem like the obvious thing to use, but I guess not to other people. 

But in the name of clarity and simplicity, let's not.

**Comment by alex-s-gardner** [comment]
I'm use to using DataFrames and YAXArray (maybe thats's changed) which are more flexible with strings and symbols... but you logic seems well justified.

**Comment by rafaqz** [comment]
Well YAX is just DD now but maybe they still transform strings to Symbol somewhere.

It means people will keep doing it instead of learning that Symbol is more suited to this task in Julia.

**Comment by asinghvi17** [comment]
BTW, if you need a name with spaces, you can create a symbol in two ways:
- `Symbol("hello there")`
- `:var"hello there"`
