### ISSUE TITLE
Documentation of invariants

### ISSUE THREAD

**Issue by ivirshup** [rafaqz/DimensionalData.jl#83]
I've got some ideas about what the invariant properties of DimensionalArrays should be, but then run into cases where they aren't true. I'm then not sure whether my mental model is wrong, or if I've found a bug. It'd be good to get some consensus on this, and document these. Potentially these could also be enforced at runtime, potentially in constructors. Here's a few of the cases I can recall:

### Size of dimensions

Should this always be true?

```julia
length.(dims(da)) == size(da) == size(data(da))
```

### Broadcasting and dimension equality

Should dimensions which broadcasting is happening over have to be equal? I.e.:

```julia
a = DimensionalArray(1:3, X(1:3))
b = DimensionalArray(1:3, X(3:-1:1))

a .+ reverse(b)  # I think this should work
a .+ b  # But shouldn't this error?
```

### Equality and dimension equality

```julia
# If this is true
dims(a::DimensionalArray) != dims(b::DimensionalArray)
# Shouldn't this be true?
a != b
```

**Comment by rafaqz** [comment]
> `length.(dims(da)) == size(da) == size(data(da))`

Mostly, but it isn't when the dim is just `X()`. It currently contains `Colon()` and doesn't know it's length. Indices are just passed to the array unchanged. But we could fix that if that should really always hold. `formatdims` could replace the colon with something length aware.

> Should dimensions which broadcasting is happening over have to be equal? I.e.:

Yes probably, but with some caveats. I've taken an incremental approach to implementing this. Currently we just check the dims are the same according to `basetypeof(x)`. But we should also check that the order is the same and other grid related comparisons. These comparisons are cheap and compile away. Checking the whole index matches exactly can be more expensive if you are doing something in a loop and the index is an array - I would like to be able to turn it off if we did implement something like that. We could have a `Strictness` trait somewhere.

Equality of `DimensionalArray` is just using the `AbstracAtrray` default. So a dimensional array will equal a normal array if the values match. Basically because I haven't written anything else,  and I'm not sure what the behaviour should be.

**Comment by ivirshup** [comment]
> Mostly, but it isn't when the dim is just X(). It currently contains Colon() and doesn't know it's length. Indices are just passed to the array unchanged. But we could fix it if that should really always hold. formatdims could replace the colon with something length aware.

This is one of the cases that made me wonder if my thinking was right. I think it would make sense for the value to have a length. It's a nice assumption to have hold, and it makes it easy to catch bugs where dimensions don't match the data. 

I'd probably implement the conversion in the outer constructors, have the size check in the inner constructor.

> Checking the whole index matches exactly can be more expensive if you are doing something in a loop and the index is an array - I would like to be able to turn it off if we did implement something like that.

I definitely think this check should happen by default. A lot of my interest in labelled arrays is that they make correctness easier. I agree there should be a way to turn this off (something `@inbounds`-y), though I also think users should drop down to the data arrays for hot loops. If any new arrays need to allocated DimensionalArrays will always take longer than just the internal arrays.

> Loading files from different sources that cover the same spatial area (or similar). The index wont always be the identical Float64 values due to the quirks of the source, even if they are representing the exact same grid.

I think it'd be difficult to have a universally appropriate method for assigning closeness, and tolerance would have to be on a case by case basis. There's also the issue of how do you deal with "closeness" which could vary with how your file was written.

What if matching was the requirement, but there was tooling to make preprocessing arrays to have the same dimensions easier? Something like xarray's [`reindex`, `reindex_like`](http://xarray.pydata.org/en/stable/generated/xarray.DataArray.reindex.html), or [`align`](http://xarray.pydata.org/en/stable/generated/xarray.align.html).

> Equality of DimensionalArray is just using the AbstracArray default. So a DimensionalArray will equal an Array if the values match. Basically because I haven't written anything else, and I'm not sure what the behaviour should be.

My preference would be similar to broadcasting. Basically:

```julia
==(A::AbstractArray, B::AbstractDimensionalArray) = A == data(B)
==(A:: AbstractDimensionalArray, B:: AbstractArray) = B == A
function ==(A:: AbstractDimensionalArray, B:: AbstractDimensionalArray)
    ...  # Data and dims have to be equal
end
```

**Comment by rafaqz** [comment]
> What if matching was the requirement, but there was tooling to make preprocessing arrays to have the same dimensions easier

One of my use cases is to load hundreds of arrays asap and run some operation on them. I don't care about checks because I know they are the same (ie close enough). I just want to be able to plot the result as a map with a shapefile. Strictness just slows down the simulation. 

In other use cases strictness would be great. But we would need a way to turn it off. Preprocessing is also not cool if it is forced. This kind of data with unreliable accuracy in the index is my core use-case. I would have to do that everywhere with everything.

**Comment by rafaqz** [comment]
> My preference would be similar to broadcasting. Basically:

Feel free to implement that! It's not a high priority for me. Also a lot of tests will need fixing, probably.

`reindex`/`align` would be good to have, also feel free to implement them.

**Comment by rafaqz** [comment]
>I'd probably implement the conversion in the outer constructors, have the size check in the inner constructor.

Current

**Comment by ivirshup** [comment]
Question about your use case, wouldn't reading the data from disk dwarf the time it'd take to compare the indices? Also, if we confirmed that the dimensions match, and it's an invariant that dims match the size of the underlying array, would it be fairly to then run your computations with `@inbounds`?

I'm giving a shot at enforcing `length.(dims(da)) == size(da) == size(data(da))`, and have run into my first incompatible test. What are these lines supposed to be testing? https://github.com/rafaqz/DimensionalData.jl/blob/a1f597c3b20f92c4aa63b1e8b69d65004a4b0f72/test/primitives.jl#L49-L51

**Comment by rafaqz** [comment]
Ok to clarify, we also often aggregate grids from disk to memory and run simulation interactively, so it does a lot of broadcasts over a lot of DimensionalArrays while you move an Interact.jl slider. That's the kind of thing I'm thinking about where performance is already limiting the use-case.

But actually, I currently broadcast over the parent data anyway... (lol). In simulations I can just check the grids once outside the loop manually, and broadcast the inner array instead of the DimensionalArray. Everywhere else checks can happen.

So lets make the index check the default I'm sold. Sorry it took so long.


`TransformedGrid` is for affine maps where the grid is rotated, or some other coordinate transform. Those lines test that you can index with `X` and `Y` when the dims are something else like Dim{:trasn1}` and `Dim{:trans2} that have a transform function that maps to `X` and `Y`. It could do with more thought tbh, but it works and people seemed to think that made sense when we discussed it in JuliaGeo

It doesn't have an index because the dims are transformed by the function. We could do the same thing we do for `Colon` dims - but the value actually doesn't matter it isn't used.

> Also, do you foresee any issues with `Dim` having the signature:

```julia
Dim{X,T<:AbstractArray,G,M} <: AbstractParametricDimension{X,T,G,M}
```

`Dim` cant have `<: AbstractArray` in the signature, as we use the same type to hold indices and selectors. Matching them is how we sort dimensions. So `T` has to be free to be anything. We could change this by duplicating all of the dim types - one for holding the index, one for indexing into it. But it could be a mess, and users would have to use both. I opted for using the same type wrapper for both the dimi index and the indexing values to reduce the amount of syntax to learn, but it has its drawbacks.

**Comment by ivirshup** [comment]
Are those broadcasts able to fuse? I think we could probably manage to just check the inputs for a fused broadcast and not have to do anything for intermediates.

> So lets make the index check the default I'm sold. Sorry it took so long.

No worries! I'm not sure how long it'll take to get around to implementing that anyways.

> TransformedGrid is for affine maps where the grid is rotated, or some other coordinate transform. Those lines test that you can index with X and Y when the dims are something else like Dim{:trasn1}andDim{:trans2} that have a transform function that maps to X and Y. It could do with more thought tbh, but it works and people seemed to think that made sense when we discussed it in JuliaGeo

Could you link me to those discussions? I'd like to see some use cases, and usage code, just to make sure I'm thinking about this right. I'll follow this up over on #85 for the specific case.

> Dim cant have T <: AbstractArray in the signature,

Yeah, this became obvious to me once I got past some failing tests.

> We could change this by duplicating all of the dim types - one for holding the index, one for indexing into it.

If you wanted to go this way, `{dim} <| {selector}` could just return a different type. I'm not sure if this is the right way to go though. `X(1)` is also nice syntax. There is an appeal to having "the one true way" though.
